### ISSUE TITLE
401 error

### ISSUE THREAD

**Issue by Nando-bog** [JerrisonChang/kf6api-py#5]
Hi Jerrison:
I'm trying to use the package but getting and authentication error when accessing the ikit-staging server URL with the following code. My password and username are fine and the server URL is ikit-staging. Has access to the api been restricted by IP or other means?

```
request_data = {
            'userName': USERNAME,
            'password': PASSWORD
        }
res = requests.post(f"{KF_URL}/auth/local", json = request_data)

```
<Response [401]>

Running it as in the Readme also gives an error:
`kf6api = KF6API(KF_URL, USERNAME, PASSWORD)`

Exception: ('Something is not right', <Response [401]>)

**Comment by JerrisonChang** [comment]
Hi Fernando!
Have you tried `https://kf6-stage.ikit.org` as your URL?

As of now, I don't think ikit server restrict api access by IP. Hope that helps!

**Comment by Nando-bog** [comment]
Thanks for the super quick reply!

Yes, the URL is correct:  I'm running this:

import os
from kf6py import KF6API
KF_URL = "https://kf6-stage.ikit.org"
USERNAME = os.environ.get("KF_USER")
PASSWORD = os.environ.get("KF_PASS")
kf6api = KF6API(KF_URL, USERNAME, PASSWORD)


Response:

Exception Traceback (most recent call last) Cell In[2], line 3 1 from kf6py
import KF6API ----> 3 kf6api = KF6API(KF_URL, USERNAME, PASSWORD) File
~/nandev/virtualenvs/kf/lib/python3.11/site-packages/kf6py/api.py:12
<https://file+.vscode-resource.vscode-cdn.net/Users/nando/nandev/kf_ai_playground/~/nandev/virtualenvs/kf/lib/python3.11/site-packages/kf6py/api.py:12>,
in KF6API.__init__(self, url, username, password) 7
<https://file+.vscode-resource.vscode-cdn.net/Users/nando/nandev/kf_ai_playground/~/nandev/virtualenvs/kf/lib/python3.11/site-packages/kf6py/api.py:7>
self.login_credential = { 8
<https://file+.vscode-resource.vscode-cdn.net/Users/nando/nandev/kf_ai_playground/~/nandev/virtualenvs/kf/lib/python3.11/site-packages/kf6py/api.py:8>
'userName': username, 9
<https://file+.vscode-resource.vscode-cdn.net/Users/nando/nandev/kf_ai_playground/~/nandev/virtualenvs/kf/lib/python3.11/site-packages/kf6py/api.py:9>
'password': password 10
<https://file+.vscode-resource.vscode-cdn.net/Users/nando/nandev/kf_ai_playground/~/nandev/virtualenvs/kf/lib/python3.11/site-packages/kf6py/api.py:10>
} 11
<https://file+.vscode-resource.vscode-cdn.net/Users/nando/nandev/kf_ai_playground/~/nandev/virtualenvs/kf/lib/python3.11/site-packages/kf6py/api.py:11>
self.KF_URL = url.strip('/ <https://file+.vscode-resource.vscode-cdn.net/> ')
---> 12
<https://file+.vscode-resource.vscode-cdn.net/Users/nando/nandev/kf_ai_playground/~/nandev/virtualenvs/kf/lib/python3.11/site-packages/kf6py/api.py:12>
self.token = self._login() 13
<https://file+.vscode-resource.vscode-cdn.net/Users/nando/nandev/kf_ai_playground/~/nandev/virtualenvs/kf/lib/python3.11/site-packages/kf6py/api.py:13>
self.author_id = None 14
<https://file+.vscode-resource.vscode-cdn.net/Users/nando/nandev/kf_ai_playground/~/nandev/virtualenvs/kf/lib/python3.11/site-packages/kf6py/api.py:14>
self.current_community = None File
~/nandev/virtualenvs/kf/lib/python3.11/site-packages/kf6py/api.py:20
<https://file+.vscode-resource.vscode-cdn.net/Users/nando/nandev/kf_ai_playground/~/nandev/virtualenvs/kf/lib/python3.11/site-packages/kf6py/api.py:20>,
in KF6API._login(self) 18
<https://file+.vscode-resource.vscode-cdn.net/Users/nando/nandev/kf_ai_playground/~/nandev/virtualenvs/kf/lib/python3.11/site-packages/kf6py/api.py:18>
res = requests.post(f"{self.KF_URL}/auth/local
<https://file+.vscode-resource.vscode-cdn.net/auth/local>", json =
self.login_credential)
19
<https://file+.vscode-resource.vscode-cdn.net/Users/nando/nandev/kf_ai_playground/~/nandev/virtualenvs/kf/lib/python3.11/site-packages/kf6py/api.py:19>
if res.status_code != 200: ---> 20
<https://file+.vscode-resource.vscode-cdn.net/Users/nando/nandev/kf_ai_playground/~/nandev/virtualenvs/kf/lib/python3.11/site-packages/kf6py/api.py:20>
raise Exception("Something is not right", res) 22
<https://file+.vscode-resource.vscode-cdn.net/Users/nando/nandev/kf_ai_playground/~/nandev/virtualenvs/kf/lib/python3.11/site-packages/kf6py/api.py:22>
return res.json()['token'] Exception: ('Something is not right', <Response
[401]>)

**Comment by JerrisonChang** [comment]
Hi Fernando, it looks like you got a 401 response during your request.

May I ask you which Python version you are running on, and what kf6py version you are using?

did you make sure your python script has correct access to your credentials?

**Comment by Nando-bog** [comment]
Thanks. My password was not loading correctly form the env. Thanks!

**Comment by JerrisonChang** [comment]
Yay! Glad that you sorted it out!
